name: build

on:
  release:
    types: [ published ]

permissions:
    contents: write


jobs:
    release:
        name: Release on GitHub
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v1

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.4

        - name: Set GOROOT for Release
          run: echo "GOROOT=${RUNNER_TOOL_CACHE}/go/1.21.4/x64" >> $GITHUB_ENV
    
        - name: Validates GO releaser config
          uses: docker://goreleaser/goreleaser:latest
          with:
            args: check
    
        - name: Create release on GitHub
          uses: docker://goreleaser/goreleaser:latest
          with:
            args: release
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    