name: build

on:
  release:
    types: [ published ]

permissions:
    contents: write


jobs:
    build-go-binary:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          goos: [windows]
          goarch: [amd64, arm64] 
          exclude:
            - goarch: arm64
              goos: windows
      steps:
        - uses: actions/checkout@v3
        - uses: wangyoucao577/go-release-action@v1.30
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: ${{ matrix.goos }}
            goarch: ${{ matrix.goarch }}
            goversion: 1.21.4
            binary_name: "tup"